#name : try { ... } catch (...) { ...}
# --
try {
     $0
} catch (${1:Exception e}) {
     // TODO: Handle this exception
}